export const NOTE_SET_ALL = 'NOTE_SET_ALL'
export const SET_QUERY_STRING = 'SET_QUERY_STRING'
export const NOTE_SET = 'NOTE_SET'
export const NOTE_APPEND = 'NOTE_APPEND'
export const NOTE_CHANGE = 'NOTE_CHANGE'
export const NOTE_REMOVE = 'NOTE_REMOVE'
export const NOTE_CREATE = 'NOTE_CREATE'
export const NOTE_DELETE = 'NOTE_DELETE'
export const NOTE_FETCH_ALL = 'NOTE_FETCH_ALL'
export const NOTE_FETCH_FOLDER = 'NOTE_FETCH_FOLDER'
export const NOTE_FETCH_TAG = 'NOTE_FETCH_TAG'
export const NOTE_FETCH_PAGE = 'NOTE_FETCH_PAGE'
export const NOTE_NEW = 'NOTE_NEW'
export const NOTETAG_SET = 'NOTETAG_SET'
export const GET_NOTE='GET_NOTE'
export default {
  NOTE_SET_ALL,
  SET_QUERY_STRING,
  NOTE_SET,
  NOTE_APPEND,
  NOTE_CHANGE,
  NOTE_REMOVE,
  NOTE_CREATE,
  NOTE_DELETE,
  NOTE_FETCH_ALL,
  NOTE_FETCH_FOLDER,
  NOTE_FETCH_TAG,
  NOTE_FETCH_PAGE,
  NOTE_NEW,
  NOTETAG_SET
}
