export const FOLDER_SET_ALL = 'FOLDER_SET_ALL'
export const FOLDER_SET = 'FOLDER_SET'
export const FOLDER_APPEND = 'FOLDER_APPEND'
export const FOLDER_CHANGE = 'FOLDER_CHANGE'
export const FOLDER_REMOVE = 'FOLDER_REMOVE'

export const FOLDER_FETCH_ALL = 'FOLDER_FETCH_ALL'
export const FOLDER_FETCH = 'FOLDER_FETCH'
export const FOLDER_CREATE = 'FOLDER_CREATE'
export const FOLDER_DELETE = 'FOLDER_DELETE'

export default {
  FOLDER_SET_ALL,
  FOLDER_SET,
  FOLDER_APPEND,
  FOLDER_CHANGE,
  FOLDER_REMOVE,
  FOLDER_FETCH_ALL,
  FOLDER_FETCH,
  FOLDER_CREATE,
  FOLDER_DELETE
}
